services:

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
     - db:/var/lib/postgresql/data

volumes:
  db: