name: Build & deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  api:
    name: Build & deploy API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache: false

    - name: Install dependencies
      run: go get ./...

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o ./build/ ./cmd/api/...
          
    - name: Deploy
      run: |
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        ssh-keyscan ${{ vars.HOST }} >> ~/.ssh/known_hosts
        eval $(ssh-agent)
        ssh-add - <<< "${{ secrets.KEY }}"
        rsync -azh --delay-updates --stats ${{ github.workspace }}/build/ ${{ vars.USERNAME }}@${{ vars.HOST }}:${{ vars.TARGET }}
        rsync -azh --delay-updates --stats ${{ github.workspace }}/internal/adapter/postgres/migrations ${{ vars.USERNAME }}@${{ vars.HOST }}:${{ vars.TARGET }}

    - name: Migrate & Restart service
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          migrate -path /var/www/stock-scout/api/migrations \
          -database "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_NAME}?sslmode=disable" up
          sudo systemctl restart stock-scout-api.service

  frontend:
    name: Build & deploy frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: cd frontend && npm ci

      - name: Build SvelteKit
        run: cd frontend && npm run build
        env:
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}

      - name: Upload to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.4.0
        with:
          source: "frontend/build"
          storageEndpoint: "${{ vars.STORAGE_ENDPOINT }}"
          storageZoneName: "${{ vars.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.STORAGE_KEY }}"
          pullZoneId: "${{ vars.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"